### ISSUE TITLE
macOS issue installing mGBA

### ISSUE THREAD

**Issue by ymaniz09** [40Cakes/pokebot-gen3#315]
First of all, I need to thank you for such amazing work!

Currently, I'm trying to set it up on my MacBook, but it fails to install the required tools:

```
Traceback (most recent call last):
  File "~/pokebot-20240319.0/pokebot.py", line 111, in <module>
    from modules.gui import PokebotGui
  File "~/pokebot-20240319.0/modules/gui/__init__.py", line 17, in <module>
    from modules.gui.emulator_screen import EmulatorScreen
  File "~/pokebot-20240319.0/modules/gui/emulator_screen.py", line 7, in <module>
    from modules.gui.debug_tabs import *
  File "~/pokebot-20240319.0/modules/gui/debug_tabs.py", line 23, in <module>
    from modules.gui.emulator_controls import DebugTab
  File "~/pokebot-20240319.0/modules/gui/emulator_controls.py", line 10, in <module>
    from modules.libmgba import LibmgbaEmulator
  File "~/pokebot-20240319.0/modules/libmgba.py", line 12, in <module>
    import mgba.audio
  File "~/pokebot-20240319.0/mgba/__init__.py", line 6, in <module>
    from ._pylib import ffi, lib  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(~/pokebot-20240319.0/mgba/_pylib.abi3.so, 0x0002): Library not loaded: @rpath/libmgba.0.10.dylib
  Referenced from: <0E612E70-C7B2-3AFD-90D9-B0D6825CA014> ~/pokebot-20240319.0/mgba/_pylib.abi3.so
  Reason: tried: '˜~/miniconda3/envs/pokebot/bin/../lib/libmgba.0.10.dylib' (no such file), '~/miniconda3/envs/pokebot/bin/../lib/libmgba.0.10.dylib' (no such file), '/usr/local/lib/libmgba.0.10.dylib' (no such file), '/usr/lib/libmgba.0.10.dylib' (no such file, not in dyld cache)
```

I also tried downloading the [libmgba-py](https://github.com/hanzi/libmgba-py/) and pasting it inside the `mgba` folder, but I have had no success so far.

Thank you!

**Comment by ymaniz09** [comment]
Actually, this was my fault!

Anaconta was messing up with my venv.
