### ISSUE TITLE
TypeError in Linux

### ISSUE THREAD

**Issue by nikitimi** [40Cakes/pokebot-gen3#329]
I've recently migrated my fork of this repository to WSL and removed Python in my Windows environment,
however upon, installing the modules prompted in the cmd, I got this traceback:

I didn't test in Windows because I removed Python, and really don't want to reinstall it.

```/bin/python3/mnt/c/linux-path/pokebot-gen3/pokebot.py
Traceback (most recent call last):
  File "/mnt/c/linux-path/pokebot-gen3/pokebot.py", line 108, in <module>
    from modules.context import context
  File "/mnt/c/linux-path/pokebot-gen3/modules/context.py", line 9, in <module>
    from modules.config import Config
  File "/mnt/c/linux-path/pokebot-gen3/modules/config/__init__.py", line 9, in <module>
    from modules.config.schemas_v1 import Battle, CatchBlock, Cheats, Discord, Keys, Logging, OBS, ProfileMetadata
  File "/mnt/c/linux-path/pokebot-gen3/modules/config/schemas_v1.py", line 13, in <module>
    class Battle(BaseConfig):
  File "/home/realsyntexia/.local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 197, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/home/realsyntexia/.local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 474, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/home/realsyntexia/.local/lib/python3.10/site-packages/pydantic/_internal/_fields.py", line 131, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "/home/realsyntexia/.local/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 226, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "/home/realsyntexia/.local/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 238, in eval_type_lenient
    return eval_type_backport(value, globalns, localns)
  File "/home/realsyntexia/.local/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 254, in eval_type_backport
    return typing._eval_type(  # type: ignore
  File "/usr/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.10/typing.py", line 693, in _evaluate
    type_ = _type_check(
  File "/usr/lib/python3.10/typing.py", line 171, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.ClassVar is not valid as type argument

**Comment by nikitimi** [comment]
Thank you, I'll try to install the versions you've stated
