### ISSUE TITLE
Support Windows on ARM

### ISSUE THREAD

**Issue by TeamBrainStorm** [40Cakes/pokebot-gen3#345]
When I run the Python script on my Surface Laptop 7, which has a Snapdragon chip in it, I get errors and the app crashes when trying to install the dependencies.

here is the log 

The following Python modules need to be checked and possibly installed:

  * confz==2.0.1
  * numpy~=1.26.1
  * Flask~=2.3.2
  * Flask-Cors~=4.0.0
  * ruamel.yaml~=0.18.2
  * pypresence~=4.3.0
  * obsws-python~=1.6.0
  * pandas~=2.1.1
  * discord-webhook~=1.2.1
  * jsonschema~=4.17.3
  * rich~=13.5.2
  * cffi~=1.16.0
  * Pillow~=10.0.1
  * sounddevice~=0.4.6
  * requests~=2.31.0
  * pyperclip3~=0.4.1
  * plyer~=2.1.0
  * notify-py~=0.3.42
  * apispec~=6.3.0
  * apispec-webframeworks~=0.5.2
  * flask-swagger-ui~=4.11.1
  * ttkthemes~=3.2.2
  * darkdetect~=0.8.0
  * show-in-file-manager~=1.1.4
  * pywin32>=306
  * psutil~=5.9.5

Install those modules? [y/N] y

Requirement already satisfied: confz==2.0.1 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (2.0.1)
Requirement already satisfied: PyYAML<7.0.0,>=5.4.1 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (from confz==2.0.1) (6.0.1)
Requirement already satisfied: pydantic<3.0.0,>=1.9.0 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (from confz==2.0.1) (2.7.4)
Requirement already satisfied: python-dotenv<2.0.0,>=0.19.2 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (from confz==2.0.1) (1.0.1)
Requirement already satisfied: toml<0.11.0,>=0.10.2 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (from confz==2.0.1) (0.10.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (from pydantic<3.0.0,>=1.9.0->confz==2.0.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.18.4 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (from pydantic<3.0.0,>=1.9.0->confz==2.0.1) (2.18.4)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\devs4\appdata\local\programs\python\python312-arm64\lib\site-packages (from pydantic<3.0.0,>=1.9.0->confz==2.0.1) (4.12.2)
Collecting numpy~=1.26.1
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\devs4\AppData\Local\Programs\Python\Python312-arm64\python.exe C:\Users\devs4\AppData\Local\Temp\pip-install-v5ydektu\numpy_3de4151f4a4a4e7093447be67b322efa\vendored-meson\meson\meson.py setup C:\Users\devs4\AppData\Local\Temp\pip-install-v5ydektu\numpy_3de4151f4a4a4e7093447be67b322efa C:\Users\devs4\AppData\Local\Temp\pip-install-v5ydektu\numpy_3de4151f4a4a4e7093447be67b322efa\.mesonpy-78p12hx6 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\devs4\AppData\Local\Temp\pip-install-v5ydektu\numpy_3de4151f4a4a4e7093447be67b322efa\.mesonpy-78p12hx6\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\devs4\AppData\Local\Temp\pip-install-v5ydektu\numpy_3de4151f4a4a4e7093447be67b322efa
      Build dir: C:\Users\devs4\AppData\Local\Temp\pip-install-v5ydektu\numpy_3de4151f4a4a4e7093447be67b322efa\.mesonpy-78p12hx6
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\devs4\AppData\Local\Temp\pip-install-v5ydektu\numpy_3de4151f4a4a4e7093447be67b322efa\.mesonpy-78p12hx6\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "C:\Users\devs4\Documents\pokebot-20240528.0\pokebot.py", line 107, in <module>
    check_requirements()
  File "C:\Users\devs4\Documents\pokebot-20240528.0\requirements.py", line 231, in check_requirements
    return update_requirements()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\devs4\Documents\pokebot-20240528.0\requirements.py", line 113, in update_requirements
    subprocess.check_call(
  File "C:\Users\devs4\AppData\Local\Programs\Python\Python312-arm64\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\devs4\\AppData\\Local\\Programs\\Python\\Python312-arm64\\python.exe', '-m', 'pip', 'install', '--disable-pip-version-check', '--no-python-version-warning', 'numpy~=1.26.1']' returned non-zero exit status 1.
Exception ignored in atexit callback: <function on_exit at 0x0000022FF62C8A40>
Traceback (most recent call last):
  File "C:\Users\devs4\Documents\pokebot-20240528.0\pokebot.py", line 24, in on_exit
    import psutil
ModuleNotFoundError: No module named 'psutil'

thanks for everything you have done!

**Comment by TeamBrainStorm** [comment]
I found a solution to my issue if you have a windows copilot PC with a snapdragon CPU if you download and install the  64bit version of python  the bot will work! here is the link to the installer i used: https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe
