### ISSUE TITLE
Error `No Module Named: confz` appearing after first start

### ISSUE THREAD

**Issue by ScottAust1n** [40Cakes/pokebot-gen3#399]
![fsfsdfsdsfd](https://github.com/user-attachments/assets/5dcb85bf-9c8b-4bf7-9c9c-ad4521e1095b)
I just installed everything from requirements and its still not opening I even clicked the pokebot.py and nothing is happening

**Comment by GreenPaint414** [comment]
necesito ayuda me sale esto

Not installing any requirements -- the bot might not work this way! Traceback (most recent call last):  File "C:\Users\ASROCK\Desktop\pokebot-gen3-main\pokebot-gen3-main\pokebot.py", line 110, in <module>    from modules.context import context  File "C:\Users\ASROCK\Desktop\pokebot-gen3-main\pokebot-gen3-main\modules\context.py", line 5, in <module>    from modules.config import Config  File "C:\Users\ASROCK\Desktop\pokebot-gen3-main\pokebot-gen3-main\modules\config\__init_ _.py", line 5, in <module>    from confz import BaseConfig, FileSource ModuleNotFoundError: No module named 'confz' Página 1
