### ISSUE TITLE
/usr/lib/libmgba.0.10.dylib no such file MacOS arm

### ISSUE THREAD

**Issue by loisglld** [40Cakes/pokebot-gen3#547]
Hello, after cloning the repo and launch a venv with `python -m venv venv`, I tried to `python pokebot.py` but I keep running into this error:

```bash
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/exceptions_hook.py", line 16, in exception_hook
    raise exc_instance
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/pokebot.py", line 138, in <module>
    startup_settings = parse_arguments(get_bot_mode_names())
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/modes/__init__.py", line 68, in get_bot_mode_names
    result.extend(mode.name() for mode in get_bot_modes())
                                          ^^^^^^^^^^^^^^^
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/modes/__init__.py", line 18, in get_bot_modes
    from .berry_blend import BerryBlendMode
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/modes/berry_blend.py", line 10, in <module>
    from ..gui.multi_select_window import Selection, ask_for_choice
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/__init__.py", line 17, in <module>
    from modules.gui.emulator_screen import EmulatorScreen
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/emulator_screen.py", line 7, in <module>
    from modules.gui.debug_tabs import *
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/debug_tabs.py", line 26, in <module>
    from modules.gui.emulator_controls import DebugTab
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/emulator_controls.py", line 10, in <module>
    from modules.libmgba import LibmgbaEmulator
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/libmgba.py", line 13, in <module>
    import mgba.audio
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/mgba/__init__.py", line 6, in <module>
    from ._pylib import ffi, lib  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/mgba/_pylib.abi3.so, 0x0002): Library not loaded: @rpath/libmgba.0.10.dylib
  Referenced from: <0E612E70-C7B2-3AFD-90D9-B0D6825CA014> /Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/mgba/_pylib.abi3.so
  Reason: tried: '/usr/lib/libmgba.0.10.dylib' (no such file, not in dyld cache)

Original exception was:
Traceback (most recent call last):
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/exceptions_hook.py", line 16, in exception_hook
    raise exc_instance
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/pokebot.py", line 138, in <module>
    startup_settings = parse_arguments(get_bot_mode_names())
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/modes/__init__.py", line 68, in get_bot_mode_names
    result.extend(mode.name() for mode in get_bot_modes())
                                          ^^^^^^^^^^^^^^^
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/modes/__init__.py", line 18, in get_bot_modes
    from .berry_blend import BerryBlendMode
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/modes/berry_blend.py", line 10, in <module>
    from ..gui.multi_select_window import Selection, ask_for_choice
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/__init__.py", line 17, in <module>
    from modules.gui.emulator_screen import EmulatorScreen
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/emulator_screen.py", line 7, in <module>
    from modules.gui.debug_tabs import *
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/debug_tabs.py", line 26, in <module>
    from modules.gui.emulator_controls import DebugTab
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/gui/emulator_controls.py", line 10, in <module>
    from modules.libmgba import LibmgbaEmulator
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/modules/libmgba.py", line 13, in <module>
    import mgba.audio
  File "/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/mgba/__init__.py", line 6, in <module>
    from ._pylib import ffi, lib  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/mgba/_pylib.abi3.so, 0x0002): Library not loaded: @rpath/libmgba.0.10.dylib
  Referenced from: <0E612E70-C7B2-3AFD-90D9-B0D6825CA014> /Users/loisgallaud/Documents/code/py/pkmn-bot/pokebot-gen3/mgba/_pylib.abi3.so
  Reason: tried: '/usr/lib/libmgba.0.10.dylib' (no such file, not in dyld cache)
```

I run on an MacBook Air M2

**Comment by Dukmos** [comment]
did you install mgba?
the python bindings use libmga from the normal mgba install on macOS and Linux.

you can install mgba on macOS via brew
https://formulae.brew.sh/formula/mgba

**Comment by loisglld** [comment]
> did you install mgba?
> 
> the python bindings use libmga from the normal mgba install on macOS and Linux.
> 
> 
> 
> you can install mgba on macOS via brew
> 
> https://formulae.brew.sh/formula/mgba

Yes I did

**Comment by ThibaultLassiaz** [comment]
Someone managed to make it work on MacOS [here](https://discord.com/channels/1057088810950860850/1139190426834833528/1325087098545508403), maybe these steps will help
